site_name: NFW Ecosystem
extra:
  version:
    provider: mike
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - md_in_html
  - meta
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  features:
    - navigation.sections
    - content.code.annotate 
plugins:
  - search
  - mike
repo_url: https://github.com/TRIPTYK/nfw-core
