site_name: NFW-core
nav:
  - Home: index.md
  - Getting started:
    - Installation: getting-started/installation.md
    - Creating the Web server: getting-started/web-server.md
    - First controller: getting-started/controller.md
    - First Middleware: getting-started/middleware.md
  - Overview:
    - Controllers: controllers.md
    - Middlewares: middlewares.md
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
theme:
  name: material
  features:
    - navigation.sections
    - content.code.annotate 
plugins:
  - search
repo_url: https://github.com/TRIPTYK/nfw-core
